services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/shuttle_monitor
      - DB_USER=postgres
      - DB_PASSWORD=100403
      - DB_SSL=false
      - PORT=8080
      - MAIL_USERNAME=alfrancisbadillapaz10@gmail.com
      - MAIL_PASSWORD=ausw wjdu olkh fszr
      - JWT_SECRET=my-very-secure-secret-key-1234567890
      - MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoiYWxmcmFuY2lzYnA0IiwiYSI6ImNtZnRqaDU2dzBsbGIyanM4cHFhbDY1MjMifQ.-ZQAt1NphjZJLxYUeMkZ7g
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=shuttle_monitor
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=100403
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
